<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

namespace SwaggerClient\models;

use \ArrayAccess;

class Log implements ArrayAccess {
  static $swaggerTypes = array(
      'type' => 'string',
      'note' => 'string',
      'details' => 'string',
      'log_date' => 'string'
  );

  static $attributeMap = array(
      'type' => 'type',
      'note' => 'note',
      'details' => 'details',
      'log_date' => 'log_date'
  );

  
  /**
  * type of log
  */
  public $type; /* string */
  /**
  * text of note
  */
  public $note; /* string */
  /**
  * details of log
  */
  public $details; /* string */
  /**
  * log date
  */
  public $log_date; /* string */

  public function __construct(array $data = null) {
    $this->type = $data["type"];
    $this->note = $data["note"];
    $this->details = $data["details"];
    $this->log_date = $data["log_date"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
